@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.ridanisaurus.emendatusenigmatica.plugin.model.deposit.sphere;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;